#!/bin/sh

# Set these paths appropriately

BIN="/b/Kaggle/readability/data/treesetup/bin"
CMD="/b/Kaggle/readability/data/treesetup/cmd"
LIB="/b/Kaggle/readability/data/treesetup/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovenian.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
