#!/bin/sh

# Set these paths appropriately

BIN="/b/Kaggle/readability/data/treesetup/bin"
CMD="/b/Kaggle/readability/data/treesetup/cmd"
LIB="/b/Kaggle/readability/data/treesetup/lib"

OPTIONS="-token -lemma -sgml -pt-with-lemma"

TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/german-abbreviations
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/german-spoken.par

$TOKENIZER -a $ABBR_LIST $* |
# tagging
$TAGGER $OPTIONS $PARFILE
