#!/bin/sh

# Set these paths appropriately

BIN="/b/Kaggle/readability/data/treesetup/bin"
CMD="/b/Kaggle/readability/data/treesetup/cmd"
LIB="/b/Kaggle/readability/data/treesetup/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/catalan-abbreviations
PARFILE=${LIB}/catalan.par

$TOKENIZER -c -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
